/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ControlPanelIndexRouteImport } from './routes/control-panel/index'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesCreateRouteImport } from './routes/categories/create'
import { Route as CategoriesCategoryIdEditRouteImport } from './routes/categories/$categoryId/edit'

const ControlPanelIndexRoute = ControlPanelIndexRouteImport.update({
  id: '/control-panel/',
  path: '/control-panel/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCreateRoute = CategoriesCreateRouteImport.update({
  id: '/categories/create',
  path: '/categories/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdEditRoute =
  CategoriesCategoryIdEditRouteImport.update({
    id: '/categories/$categoryId/edit',
    path: '/categories/$categoryId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/categories/create': typeof CategoriesCreateRoute
  '/categories/': typeof CategoriesIndexRoute
  '/control-panel/': typeof ControlPanelIndexRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
}
export interface FileRoutesByTo {
  '/categories/create': typeof CategoriesCreateRoute
  '/categories': typeof CategoriesIndexRoute
  '/control-panel': typeof ControlPanelIndexRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/categories/create': typeof CategoriesCreateRoute
  '/categories/': typeof CategoriesIndexRoute
  '/control-panel/': typeof ControlPanelIndexRoute
  '/categories/$categoryId/edit': typeof CategoriesCategoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/categories/create'
    | '/categories/'
    | '/control-panel/'
    | '/categories/$categoryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/categories/create'
    | '/categories'
    | '/control-panel'
    | '/categories/$categoryId/edit'
  id:
    | '__root__'
    | '/categories/create'
    | '/categories/'
    | '/control-panel/'
    | '/categories/$categoryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CategoriesCreateRoute: typeof CategoriesCreateRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ControlPanelIndexRoute: typeof ControlPanelIndexRoute
  CategoriesCategoryIdEditRoute: typeof CategoriesCategoryIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/control-panel/': {
      id: '/control-panel/'
      path: '/control-panel'
      fullPath: '/control-panel/'
      preLoaderRoute: typeof ControlPanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/create': {
      id: '/categories/create'
      path: '/categories/create'
      fullPath: '/categories/create'
      preLoaderRoute: typeof CategoriesCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId/edit': {
      id: '/categories/$categoryId/edit'
      path: '/categories/$categoryId/edit'
      fullPath: '/categories/$categoryId/edit'
      preLoaderRoute: typeof CategoriesCategoryIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  CategoriesCreateRoute: CategoriesCreateRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ControlPanelIndexRoute: ControlPanelIndexRoute,
  CategoriesCategoryIdEditRoute: CategoriesCategoryIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
